nelmio_api_doc:
  documentation:
    components:
      securitySchemes:
        Sky-authorization:
          type: apiKey
          name: Sky-authorization
          in: header
    info:
      title: Star API
      description: Star API
      version: 1.0.0
  areas:
    path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
      - ^/api(?!/doc$)